In [ ]:
 import numpy as np



List Vs Numpy-Time Taken

In [ ]:
from time import process_time


Time taken by a list


In [ ]:
python_list =[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0007178569999997109


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)


0.0006756990000003071


Numpy Array

In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#creating a 2d array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c= np.array([(1,3,5,8),(5,6,7,8)],dtype=float)
print(c)

[[1. 3. 5. 8.]
 [5. 6. 7. 8.]]


In [ ]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an idendity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.51649626 0.80849879 0.38998573 0.78601686]
 [0.38981572 0.6872396  0.50081884 0.16132135]
 [0.56350904 0.27340261 0.18227275 0.598487  ]]


In [ ]:
#create a numpy array with integer values with  specific range
c=np.random.randint(10,20,(3,5))
print(c)

[[19 19 11 14 18]
 [12 16 16 19 12]
 [19 19 18 12 15]]


In [ ]:
#array of evenly spaced values-->specify the number of values require
d= np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values-->specify the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert a list to numpy array
list2=[10,20,20,20,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[13 69 59 82 89]
 [38 63 15 34 11]
 [49 85 86 78 72]
 [72 21 30 60 79]
 [53 39 45 23 50]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of elements in array
print(c.size)

25


In [ ]:
#checking the data type of values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 5 0]
 [1 4 6]
 [2 7 2]]
[[11 15 17]
 [15 17 19]
 [16 19 17]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[18 20 17]
 [16 21 25]
 [18 26 19]]
[[ -4 -10 -17]
 [-14 -13 -13]
 [-14 -12 -15]]
[[ 77  75   0]
 [ 15  68 114]
 [ 32 133  34]]
[[0.63636364 0.33333333 0.        ]
 [0.06666667 0.23529412 0.31578947]
 [0.125      0.36842105 0.11764706]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 20 17]
 [16 21 25]
 [18 26 19]]
[[ -4 -10 -17]
 [-14 -13 -13]
 [-14 -12 -15]]
[[ 77  75   0]
 [ 15  68 114]
 [ 32 133  34]]
[[0.63636364 0.33333333 0.        ]
 [0.06666667 0.23529412 0.31578947]
 [0.125      0.36842105 0.11764706]]


Array Manipulation

In [ ]:
#transpose
trans=np.transpose(a)
print(trans)
print(trans.shape)

[[7 1 2]
 [5 4 7]
 [0 6 2]]
(3, 3)


In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 5 8]
 [5 1 6]]
(2, 3)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[9 5]
 [5 1]
 [8 6]]
(3, 2)


In [ ]:
#reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 7 2]
 [7 4 1]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)
print(b.shape)


[[3 7]
 [2 7]
 [4 1]]
(3, 2)
